/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef EXAMPLE_SDL3_FLECS_BAKE_CONFIG_H
#define EXAMPLE_SDL3_FLECS_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <EgCameras.h>
#include <EgShapes.h>
#include <EgSpatials.h>
#include <EgKeyboards.h>
#include <EgWindows.h>
#include <EgCamcontrols.h>
#include <EgFs.h>
#include <EgBase.h>
#include <EgGlslang.h>
#include <flecs.h>
#include <egmisc.h>
#include <egmath.h>
#include <ecsx.h>

#endif

