/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef TEST_RAYLIB_BAKE_CONFIG_H
#define TEST_RAYLIB_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <EgCameras.h>
#include <EgShapes.h>
#include <EgMeshes.h>
#include <EgSpatials.h>
#include <EgBase.h>
#include <EgKeyboards.h>
#include <EgCamcontrols.h>
#include <ecsx.h>

#endif

